version: '3.7'

services:
  currency-exchange:
    image: ninxtr/currency-exchange-service-0.0.1-snapshot
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
#      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  currency-conversion:
      image: ninxtr/currency-conversion-service-0.0.1-snapshot
      mem_limit: 700m
      ports:
        - "8100:8100"
      networks:
        - currency-network
      depends_on:
        - naming-server
      environment:
        EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
        MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
#        SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  api-gateway:
    image: ninxtr/api-gateway-0.0.1-snapshot
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://zipkin-server:9411/api/v2/spans
#      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/


  naming-server:
    image: ninxtr/naming-server-0.0.1-snapshot
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - currency-network

  #docker run -p 9411:9411 openzipkin/zipkin
  zipkin-server:
    image: openzipkin/zipkin
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    restart: always #Restart if there is a problem starting up



networks:
  currency-network: